### ISSUE TITLE
Allow embedding into other components

### ISSUE THREAD

**Issue by p-himik** [gadfly361/re-surface#8]
For example, I'd like to be able to create persistent small side panels with buttons that toggle other side panels. Just like the Project panel and other panels of IntelliJ IDEA.
Right now, I don't think it's feasible with `re-surface`.
If I'm wrong, an example would be much appreciated!

**Comment by gadfly361** [comment]
@p-himik You are correct that that it is not feasibly with re-surface. Currently, the idea has been only one side panel (on each side), one dimmer, one modal, etc. ever exists ... you just selectively promote them into what is visible to a user.

Regarding re-surface, I don't anticipate a rewrite to support this feature (it would cause a lot of breaking changes). 

However, as an aside, I am considering creating an alternative project that is much more conducive to nesting and swappable components ... it would just be a while until I get there.
